# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'baicanhan.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sys
import imag1
import imag2
import imag3


class Ui_Canhan(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(676, 567)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(40, 20, 151, 121))
        self.label.setStyleSheet("image: url(:/my1/Screenshot 2023-10-12 103935.png);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(180, 60, 491, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalSlider = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider.setGeometry(QtCore.QRect(20, 320, 161, 21))
        self.horizontalSlider.setMinimum(16)
        self.horizontalSlider.setMaximum(30)
        self.horizontalSlider.setProperty("value", 23)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(20, 400, 71, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(130, 400, 71, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(500, 180, 131, 141))
        self.label_3.setStyleSheet("image: url(:/my2/1.png);")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(10, 479, 661, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(40, 190, 121, 111))
        font = QtGui.QFont()
        font.setPointSize(50)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.horizontalSlider_2 = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider_2.setGeometry(QtCore.QRect(500, 340, 131, 21))
        self.horizontalSlider_2.setMinimum(1)
        self.horizontalSlider_2.setMaximum(3)
        self.horizontalSlider_2.setPageStep(10)
        self.horizontalSlider_2.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_2.setObjectName("horizontalSlider_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(530, 400, 71, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName("pushButton_3")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(20, 160, 161, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(240, 190, 181, 160))
        self.label_7.setStyleSheet("image: url(:/my3/fan_off.png);")
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(250, 310, 56, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(350, 310, 56, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setObjectName("pushButton_5")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 676, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)


        self.pushButton.clicked.connect(self.allon)
        self.pushButton_2.clicked.connect(self.alloff)
        self.pushButton_4.setEnabled(False)
        self.pushButton_5.setEnabled(False)
        self.horizontalSlider.setEnabled(False)
        self.horizontalSlider_2.setEnabled(False)
        self.pushButton_3.clicked.connect(QtWidgets.qApp.quit)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "ĐIỀU KHIỂN CÁC THIẾT BỊ "))
        self.pushButton.setText(_translate("MainWindow", "ON"))
        self.pushButton_2.setText(_translate("MainWindow", "OFF"))
        self.label_4.setText(_translate("MainWindow", "Program By Nguyễn Phước Dư-21119327"))
        self.label_5.setText(_translate("MainWindow", "23"))
        self.pushButton_3.setText(_translate("MainWindow", "EXIT"))
        self.label_6.setText(_translate("MainWindow", "NHIỆT ĐỘ MÁY LẠNH"))
        self.pushButton_4.setText(_translate("MainWindow", "ON"))
        self.pushButton_5.setText(_translate("MainWindow", "OFF"))

    def allon(self):
        self.label_3.setStyleSheet("image: url(:/my2/2.png);")
        self.label_7.setStyleSheet("image: url(:/my3/fan_running.png);")
        self.pushButton_4.setEnabled(True)
        self.pushButton_5.setEnabled(True)
        self.horizontalSlider.setEnabled(True)
        self.horizontalSlider_2.setEnabled(True)
        self.pushButton_4.clicked.connect(self.on)
        self.pushButton_5.clicked.connect(self.off)
        self.horizontalSlider.valueChanged.connect(self.change)
        self.horizontalSlider_2.valueChanged.connect(self.change1)
    def alloff(self):
        self.label_3.setStyleSheet("image: url(:/my2/1.png);")
        self.label_7.setStyleSheet("image: url(:/my3/fan_off.png);")     
        self.pushButton_4.setEnabled(False)
        self.pushButton_5.setEnabled(False)
        self.horizontalSlider.setEnabled(False)
        self.horizontalSlider_2.setEnabled(False)
    def on(self):
            self.label_7.setStyleSheet("image: url(:/my3/fan_running.png);")
            self.horizontalSlider.setEnabled(True)
    def off(self):
            self.label_7.setStyleSheet("image: url(:/my3/fan_off.png);")
            self.horizontalSlider.setEnabled(False)
    def change(self,value):
        self.label_5.setText(str(value))
    def change1(self,value):
        if(value==1): 
            self.label_3.setStyleSheet("image: url(:/my2/2.png);")
        if(value==2): 
            self.label_3.setStyleSheet("image: url(:/my2/3.png);")
        if(value==3): 
            self.label_3.setStyleSheet("image: url(:/my2/4.png);")

        
if __name__ == "__main__":
     import sys
     app = QtWidgets.QApplication(sys.argv)
     MainWindow = QtWidgets.QMainWindow()
     ui = Ui_Canhan()
     ui.setupUi(MainWindow)
     MainWindow.show()
     sys.exit(app.exec_())
